name: reviser
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  go_router: ^10.0.0
  
  logger: ^2.0.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter



dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
